version: "3.7"
services:
  web:
    build:
      context: .
      target: dev
    stdin_open: true
    tty: true
    command: ["node", "app.js"]
    volumes:
      - ".:/usr/src/app"
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: "postgres:10"
    environment:
      POSTGRES_PASSWORD: db_password
